section: screens
	kasa11:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
	SVF15A17CLB:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
	 MBP-de-Anibal.kasa:
	 	halfDuplexCapsLock = false
	 	halfDuplexNumLock = false
	 	halfDuplexScrollLock = false
	 	xtestIsXineramaUnaware = false
	 	switchCorners = none
	 	switchCornerSize = 0
	MBP-de-ms.kasa:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
end

section: aliases
end

section: links
	kasa11:
		down = SVF15A17CLB
		left = MBP-de-Anibal.kasa
		right = MBP-de-ms.kasa
	SVF15A17CLB:
		up = kasa11
	MBP-de-Anibal.kasa:
		right = kasa11
	MBP-de-ms.kasa:
		left = kasa11
end

section: options
	protocol = synergy
	relativeMouseMoves = false
	win32KeepForeground = false
	disableLockToScreen = false
	clipboardSharing = true
	clipboardSharingSize = 3072000
	switchCorners = none
	switchCornerSize = 20
end

