# By default, Makefile targets are "file targets" - they are used to build files from other files. Make assumes its target is a file, and this makes writing Makefiles relatively easy:
.PHONY  clean   # if I have a file or dir call clean, this will make to ignore and we can use word clean as a target
clean:
	rm -rf ./*
